name: Bug Report
description: Report a bug or issue with the project.
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Please describe the bug you encountered.**

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-check
      description: Please confirm that you have searched for duplicate issues before creating this one.
      options:
        - label: I have searched the existing issues and none cover this bug.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
      placeholder: "Detailed description of the bug"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide the steps to reproduce the bug.
      placeholder: "1. Step one\n2. Step two\n3. Step three"
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "Expected behavior"
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "Actual behavior"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment (e.g., OS, GPU, profile, etc.).
      placeholder: "Environment details"
    validations:
      required: true

  - type: input
    id: additional
    attributes:
      label: Additional Information
      description: Provide any additional information that may be relevant (e.g., logs, screenshots).
      placeholder: "Any additional information that may be relevant"

  - type: input
    id: version
    attributes:
      label: Version
      description: Provide the version of the project where you encountered the bug.
      placeholder: "Version number"

  - type: markdown
    attributes:
      value: |
        **Please ensure the following setup checklist has been reviewed before submitting the bug report.**

  - type: checkboxes
    id: general-setup-checklist
    attributes:
      label: Setup Checklist
      description: Verify the following general aspects of your setup.
      options:
        - label: Confirm that you have followed the installation instructions in the project’s documentation.
        - label: Check that you are using the latest version of the project.
        - label: Verify disk space availability for model storage and data processing.
        - label: Ensure that you have the necessary permissions to run the project.

  - type: checkboxes
    id: nvidia-setup-checklist
    attributes:
      label: NVIDIA GPU Setup Checklist
      description: Verify the following aspects of your NVIDIA GPU setup.
      options:
        - label: Check that the all CUDA dependencies are installed and are compatible with your GPU (refer to [CUDA's documentation](https://docs.nvidia.com/deploy/cuda-compatibility/#frequently-asked-questions))
        - label: Ensure an NVIDIA GPU is installed and recognized by the system (run `nvidia-smi` to verify).
        - label: Ensure proper permissions are set for accessing GPU resources.
        - label: Docker users - Verify that the NVIDIA Container Toolkit is configured correctly (e.g. run `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`)
